# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: sudo apt install -y build-essential libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-xinerama0-dev libxkbcommon-dev libxkbcommon-x11-dev

      # Runs a set of commands using the runners shell
      - name: Download Qt Sources
        run: |
          wget -q https://download.qt.io/archive/qt/5.15/5.15.1/single/qt-everywhere-src-5.15.1.zip
      - name: Building
        run: |
          unzip -q qt-everywhere-src-5.15.1.zip
          cd qt-everywhere-src-5.15.1
          ./configure -static -prefix ../out
          make -j$(nproc)
          make install
      - name: Finalizing
        run: tar cJf qt.tar.xz out/*
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: qt.tar.xz
          asset_name: qt.tar.xz
          tag: bruh
          overwrite: true
