# This is a basic workflow to help you get started with Actions

name: Qt

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y build-essential crossbuild-essential-arm64
          sudo apt-get install -y libgl1-mesa-dev:arm64 libfontconfig1-dev:arm64 libfreetype6-dev:arm64 libx11-dev:arm64 libx11-xcb-dev:arm64 libxext-dev:arm64 libxfixes-dev:arm64 libxi-dev:arm64 libxrender-dev:arm64 libxcb1-dev:arm64 libxcb-glx0-dev:arm64 libxcb-keysyms1-dev:arm64 libxcb-image0-dev:arm64 libxcb-shm0-dev:arm64 libxcb-icccm4-dev:arm64 libxcb-sync0-dev:arm64 libxcb-xfixes0-dev:arm64 libxcb-shape0-dev:arm64 libxcb-randr0-dev:arm64 libxcb-render-util0-dev:arm64 libxcb-xinerama0-dev:arm64 libxkbcommon-dev:arm64 libxkbcommon-x11-dev:arm64

      # Runs a set of commands using the runners shell
      - name: Download Qt Sources
        run: |
          wget -q https://download.qt.io/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz
      - name: Building
        run: |
          tar xJf qt-everywhere-src-5.15.2.tar.xz
          cd qt-everywhere-src-5.15.2
          ./configure -release -opensource -confirm-license -nomake examples -nomake tests -prefix $GITHUB_WORKSPACE/qt
          make -j$(nproc)
          make install
      - name: Finalizing
        run: tar cJf qt.tar.xz qt
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: qt.tar.xz
          asset_name: qt.tar.xz
          tag: bruh
          overwrite: true
